import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Template</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col justify-center items-center w-screen h-screen">
        <div>
          <h3 className="mb-2 text-4xl font-bold text-center text-black drop-shadow-sm">
            Custom Template
          </h3>
          <p className="mb-2">
            NextJs + Typescript + TailwindCss + Eslint + Prettier
          </p>
          <p className="text-center">
            GitHub{' '}
            <a href="https://github.com/adalbertopc" className="text-blue-600">
              @adalbertopc
            </a>
          </p>
        </div>
      </div>
    </div>
  );
}
